#!/bin/bash

# List files in the current directory in long format
echo "Current Directory:"
ls -la

# Move up one directory (parent)
cd ..

# List files in the parent directory in long format
echo "Parent Directory:"
ls -la

# Change directory to /boot
cd /boot

# List files in the /boot directory in long format
echo "/boot Directory:"
ls -la
